[package]
name = "narwhal-typed-store"
version.workspace = true
license = "Apache-2.0"
authors = [
    "Grant Kee <grant.kee@telco.in>",
    "Francois Garillot <francois@mystenlabs.com>",
]
description = "a typed database interface"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
bcs = { workspace = true }
bincode = { workspace = true }
collectable = { workspace = true }
eyre = { workspace = true }
fdlimit = { workspace = true }
once_cell = { workspace = true }
tap = { workspace = true }
prometheus = { workspace = true }
hdrhistogram = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }
tracing = { workspace = true }
telcoin-macros = { workspace = true }
ouroboros = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
itertools = { workspace = true }
tn-types = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
redb = { version = "2.1.1", optional = true }
rocksdb = { version = "0.22.0", features = [
    "snappy",
    "lz4",
    "zstd",
    "zlib",
    "multi-threaded-cf",
], default-features = false, optional = true }
# mdbx
reth-libmdbx = { workspace = true, optional = true, features = [
    "return-borrowed",
    "read-tx-timeouts",
] }
page_size = { version = "0.6.0", optional = true }


[dev-dependencies]
tempfile = { workspace = true }
once_cell = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rstest = { workspace = true }
rand = { workspace = true }
syn = { workspace = true }
uint = { workspace = true }

# Most packages should depend on sui-simulator instead of directly on msim, but for typed-store
# that creates a circular dependency.
#[target.'cfg(msim)'.dependencies]
#msim = { workspace = true }

[features]
redb = ["dep:redb"]
rocksdb = ["dep:rocksdb"]
reth-libmdbx = ["dep:reth-libmdbx", "dep:page_size"]
default = ["reth-libmdbx"]
