[package]
name = "narwhal-typed-store"
version.workspace = true
license = "Apache-2.0"
authors = [
    "Grant Kee <grant.kee@telco.in>",
    "Francois Garillot <francois@mystenlabs.com>",
    "Steven Stanfield <steve@telcoin.org>",
]
description = "a typed database interface"
edition = "2021"
publish = false

[dependencies]
eyre = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
ouroboros = { workspace = true }
tn-types = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }

# redb backend
redb = { version = "2.1.1", optional = false }

# Rocks DB backend
rocksdb = { version = "0.22.0", features = [
    "snappy",
    "lz4",
    "zstd",
    "zlib",
    "multi-threaded-cf",
], default-features = false, optional = true }
thiserror = { workspace = true, optional = true } # For rocks...
fdlimit = { workspace = true, optional = true } # For rocks...
telcoin-macros = { workspace = true, optional = true } # For rocks...

# mdbx backend- default
reth-libmdbx = { workspace = true, optional = true, features = [
    "return-borrowed",
    "read-tx-timeouts",
] }
page_size = { version = "0.6.0", optional = true }


[dev-dependencies]
tempfile = { workspace = true }
uint = { workspace = true }     # For rocks tests.

[features]
redb = []
rocksdb = ["dep:rocksdb", "dep:thiserror", "dep:fdlimit", "dep:telcoin-macros"]
reth-libmdbx = ["dep:reth-libmdbx", "dep:page_size"]
default = ["reth-libmdbx"]
