[package]
name = "tn-batch-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors = [
    "Grant Kee <grant@telcoin.org>",
    "Steven Stanfield <steve@telcoin.org>",
]

[dependencies]
tn-types = { workspace = true }
tn-reth = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tracing = { workspace = true }

metrics = { workspace = true }
thiserror = { workspace = true }
alloy-rlp = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
# unit tests
tn-test-utils = { workspace = true }
assert_matches = { workspace = true }
tempfile = { workspace = true }
eyre = { workspace = true }
tn-network-libp2p = { workspace = true }

# integration tests
prometheus = { workspace = true }
tn-worker = { workspace = true }
tn-network-types = { workspace = true }
tn-storage = { workspace = true }
tn-batch-validator = { workspace = true }
tn-engine = { workspace = true }
tn-batch-builder = { workspace = true, features = ["test-utils"] }

[features]
default = []
test-utils = []
