[package]
name = "tn-node-traits"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
exclude.workspace = true

[dependencies]
tn-types = { workspace = true }
reth-chainspec = { workspace = true }
reth-db = { workspace = true }
reth-engine-primitives = { workspace = true }
reth-evm = { workspace = true }
reth-evm-ethereum = { workspace = true }
reth-consensus = { workspace = true }
reth-node-builder = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-primitives = { workspace = true }
reth-provider = { workspace = true }
reth-revm = { workspace = true }
reth-trie-db = { workspace = true }
serde = { workspace = true }
alloy = { workspace = true, features = ["rpc"] }

[lints]
workspace = true
