[package]
name = "narwhal-storage"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
authors = [
    "Grant Kee <grant.kee@telco.in>",
    "Mysten Labs <build@mystenlabs.com>",
]
publish = false

[dependencies]
fastcrypto.workspace = true
telcoin-sync.workspace = true
tracing.workspace = true
tn-types = { workspace = true }
narwhal-typed-store = { workspace = true }
telcoin-macros.workspace = true
eyre = { workspace = true }

[dev-dependencies]
tn-types = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
futures.workspace = true
