---
header_num_of_batches_threshold: 5
max_header_num_of_batches: 10
max_header_delay: 1s
min_header_delay: 1s
gc_depth: 50
sync_retry_delay: 5s
sync_retry_nodes: 3
max_batch_delay: 1s
max_concurrent_requests: 500000
batch_vote_timeout:
  secs: 10
  nanos: 0
basefee_address: "0x9999999999999999999999999999999999999999"
