services:
  # build image once
  telcoin-base:
    image: local-telcoin-network:latest
    build:
      context: ../
      dockerfile: etc/Dockerfile

  # use built image for all 4 services
  setup1:
    image: local-telcoin-network:latest
    depends_on:
      - telcoin-base
    environment:
      - NARWHAL_HOST=10.10.0.21
      - EXECUTION_ADDRESS=0x1111111111111111111111111111111111111111
    user: "root"
    command:
      - "bash"
      - "/setup_validator.sh"
    volumes:
      - ./setup_validator.sh:/setup_validator.sh
      - validator1-data:/home/nonroot/data
  setup2:
    image: local-telcoin-network:latest
    depends_on:
      - telcoin-base
    environment:
      - NARWHAL_HOST=10.10.0.22
      - EXECUTION_ADDRESS=0x2222222222222222222222222222222222222222
    user: "root"
    command:
      - "bash"
      - "/setup_validator.sh"
    volumes:
      - ./setup_validator.sh:/setup_validator.sh
      - validator2-data:/home/nonroot/data
  setup3:
    image: local-telcoin-network:latest
    depends_on:
      - telcoin-base
    environment:
      - NARWHAL_HOST=10.10.0.23
      - EXECUTION_ADDRESS=0x3333333333333333333333333333333333333333
    user: "root"
    command:
      - "bash"
      - "/setup_validator.sh"
    volumes:
      - ./setup_validator.sh:/setup_validator.sh
      - validator3-data:/home/nonroot/data
  setup4:
    image: local-telcoin-network:latest
    depends_on:
      - telcoin-base
    environment:
      - NARWHAL_HOST=10.10.0.24
      - EXECUTION_ADDRESS=0x4444444444444444444444444444444444444444
    user: "root"
    command:
      - "bash"
      - "/setup_validator.sh"
    volumes:
      - ./setup_validator.sh:/setup_validator.sh
      - validator4-data:/home/nonroot/data

  # create and distribute committee / worker cache files
  comittee:
    image: local-telcoin-network:latest
    user: "root"
    command: >
      bash -c "
        whoami &&
        cp -r /home/nonroot/data/validator-*/genesis/validators /home/nonroot/data/genesis/ &&
        /usr/local/bin/telcoin genesis create-committee --datadir /home/nonroot/data &&
        cp -r /home/nonroot/data/genesis/committee.yaml /home/nonroot/data/genesis/worker_cache.yaml /home/nonroot/data/validator-1/genesis/ &&
        cp -r /home/nonroot/data/genesis/committee.yaml /home/nonroot/data/genesis/worker_cache.yaml /home/nonroot/data/validator-2/genesis/ &&
        cp -r /home/nonroot/data/genesis/committee.yaml /home/nonroot/data/genesis/worker_cache.yaml /home/nonroot/data/validator-3/genesis/ &&
        cp -r /home/nonroot/data/genesis/committee.yaml /home/nonroot/data/genesis/worker_cache.yaml /home/nonroot/data/validator-4/genesis/ &&
        chown -R 1101:1101 /home/nonroot/data
      "
    depends_on:
      - setup1
      - setup2
      - setup3
      - setup4
    volumes:
      - sharedgenesisdir:/home/nonroot/data/genesis
      - validator1-data:/home/nonroot/data/validator-1
      - validator2-data:/home/nonroot/data/validator-2
      - validator3-data:/home/nonroot/data/validator-3
      - validator4-data:/home/nonroot/data/validator-4

  # start nodes
  validator1:
    image: local-telcoin-network:latest
    depends_on:
      - comittee
    environment:
      - RUST_LOG=info,execution=debug
    command: >
      /usr/local/bin/telcoin node
      --datadir /home/nonroot/data
      --dev
      --chain adiri
      --http.addr 0.0.0.0
      --http.port 8545
      --public-key 0223382261d641424b8d8b63497a811c56f85ee89574f9853474c3e9ab0d690d99
    ports:
      - 8545:8545
    volumes:
      - validator1-data:/home/nonroot/data
    networks:
      validators:
        ipv4_address: 10.10.0.21
  validator2:
    image: local-telcoin-network:latest
    depends_on:
      - comittee
    command: >
      /usr/local/bin/telcoin node
      --datadir /home/nonroot/data
      --dev
      --chain adiri
      --http.addr 0.0.0.0
      --http.port 8545
      --public-key 0223382261d641424b8d8b63497a811c56f85ee89574f9853474c3e9ab0d690d99
    ports:
      - 8544:8545
    volumes:
      - validator2-data:/home/nonroot/data
    networks:
      validators:
        ipv4_address: 10.10.0.22
  validator3:
    image: local-telcoin-network:latest
    depends_on:
      - comittee
    command: >
      /usr/local/bin/telcoin node
      --datadir /home/nonroot/data
      --dev
      --chain adiri
      --http.addr 0.0.0.0
      --http.port 8545
      --public-key 0223382261d641424b8d8b63497a811c56f85ee89574f9853474c3e9ab0d690d99
    ports:
      - 8543:8545
    volumes:
      - validator3-data:/home/nonroot/data
    networks:
      validators:
        ipv4_address: 10.10.0.23
  validator4:
    image: local-telcoin-network:latest
    depends_on:
      - comittee
    command: >
      /usr/local/bin/telcoin node
      --datadir /home/nonroot/data
      --dev
      --chain adiri
      --http.addr 0.0.0.0
      --http.port 8545
      --public-key 0223382261d641424b8d8b63497a811c56f85ee89574f9853474c3e9ab0d690d99
    ports:
      - 8542:8545
    volumes:
      - validator4-data:/home/nonroot/data
    networks:
      validators:
        ipv4_address: 10.10.0.24

volumes:
  validator1-data:
  validator2-data:
  validator3-data:
  validator4-data:
  sharedgenesisdir:

networks:
  validators:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
