[package]
name = "telcoin-macros"
authors = [
    "Grant Kee <grant.kee@telco.in>",
    "Mysten Labs <build@mystenlabs.com>",
]
version.workspace = true
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(msim)',
    'cfg(fail_points)',
] }
