[package]
name = "tn-primary"
version.workspace = true
license = "Apache-2.0"
authors = [
    "Grant Kee <grant@telcoin.org>",
    "Steven Stanfield <steve@telcoin.org>",
    "Mysten Labs <build@mystenlabs.com>",
]
publish = false
edition = "2021"

[dependencies]
eyre = { workspace = true }
backoff = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "sync",
    "rt",
    "macros",
    "time",
    "test-util",
] }
tokio-stream = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tap = { workspace = true }

fastcrypto = { workspace = true }
fastcrypto-tbls = { workspace = true }
tn-network = { workspace = true }
tn-network-types = { workspace = true }
tn-types = { workspace = true }
tn-config = { workspace = true }
tn-storage = { workspace = true }
tn-utils = { workspace = true }
consensus-metrics = { workspace = true }
tn-primary-metrics = { workspace = true }

anemo = { workspace = true }
anemo-tower = { workspace = true }

[dev-dependencies]
dashmap = { workspace = true }
async-trait = { workspace = true }
criterion = { workspace = true }
futures = { workspace = true }
tn-executor = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true }
tn-node = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
tn-test-utils = { workspace = true }
tracing = { workspace = true }
tn-worker = { workspace = true }
tn-storage = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
tn-batch-validator = { workspace = true, features = ["test-utils"] }
reth = { workspace = true }
