[package]
name = "narwhal-primary"
version.workspace = true
license = "Apache-2.0"
authors = [
    "Grant Kee <grant.kee@telco.in>",
    "Mysten Labs <build@mystenlabs.com>",
]
publish = false
edition = "2021"

[dependencies]
eyre = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
bcs = { workspace = true }
reth-primitives = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "sync",
    "rt",
    "macros",
    "time",
    "test-util",
] }
tower = { workspace = true }
tracing = { workspace = true }
tap = { workspace = true }

fastcrypto = { workspace = true }
fastcrypto-tbls = { workspace = true }
narwhal-network = { workspace = true }
narwhal-network-types = { workspace = true }
tn-types = { workspace = true }
narwhal-storage = { workspace = true }
narwhal-typed-store = { workspace = true }
telcoin-macros = { workspace = true }

telcoin-sync = { workspace = true }
consensus-metrics = { workspace = true }
narwhal-primary-metrics = { workspace = true }

anemo = { workspace = true }
anemo-tower = { workspace = true }

[dev-dependencies]
dashmap = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
criterion = { workspace = true }
futures = { workspace = true }
narwhal-executor = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true }
tn-node = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
narwhal-test-utils = { workspace = true }
tracing = { workspace = true }
narwhal-worker = { workspace = true }
narwhal-storage = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
reth-tracing = { workspace = true }
tn-batch-validator = { workspace = true, features = ["test-utils"] }
reth = { workspace = true }

[features]
default = []
benchmark = []
test-utils = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark"]
