[package]
name = "tn-batch-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors = [
    "Grant Kee <grant@telcoin.org>",
    "Steven Stanfield <steve@telcoin.org>",
]

[dependencies]
tn-types = { workspace = true }
reth-provider = { workspace = true }
reth-node-types = { workspace = true }
tracing = { workspace = true }
reth-rpc-eth-types = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
# unit tests
tokio = { workspace = true, features = ["sync", "time"] }
tn-node-traits = { workspace = true }
tn-test-utils = { workspace = true }
reth-blockchain-tree = { workspace = true }
reth-chainspec = { workspace = true }
reth-consensus = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-db = { workspace = true, features = ["test-utils"] }
reth-beacon-consensus = { workspace = true }
reth-db-common = { workspace = true }
assert_matches = { workspace = true }

[features]
default = []
test-utils = []
