[package]
name = "tn-batch-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tn-types = { workspace = true }
reth-consensus = { workspace = true }
reth-provider = { workspace = true }
reth-primitives = { workspace = true }
reth-db = { workspace = true }
reth-revm = { workspace = true }
reth-blockchain-tree = { workspace = true }
reth-evm = { workspace = true }
alloy-rlp = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
# unit tests
tokio = { workspace = true, features = ["sync", "time"] }
tn-types = { workspace = true, features = ["test-utils"] }
reth-tracing = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-node-core = { workspace = true }
reth = { workspace = true }
reth-beacon-consensus = { workspace = true }
reth-primitives = { workspace = true, features = ["test-utils"]}
reth-db-common = { workspace = true }

# integration tests

[features]
default = []
test-utils = []
