[package]
name = "mem-utils-derive"
version.workspace = true
authors = [
    "Parity Technologies <admin@parity.io>",
    "Grant Kee <grant.kee@telco.in>",
]
license = "MIT OR Apache-2.0"
description = "Crate for memory reporting"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
rust-version.workspace = true
publish = false

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
synstructure = "0.12"
