[package]
name = "tn-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
tn-types = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }

reth-primitives = { workspace = true }
reth-chainspec = { workspace = true }
reth-tokio-util = { workspace = true }
reth-revm = { workspace = true }
reth-stages = { workspace = true }
reth-provider = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-payload-builder = { workspace = true }
reth-rpc-types = { workspace = true }
reth-beacon-consensus = { workspace = true }
alloy-rlp = { workspace = true }

consensus-metrics = { workspace = true }
narwhal-executor = { workspace = true }

# for components mod
reth-config = { workspace = true }
reth-tasks = { workspace = true }
#revm-inspectors = { workspace = true }
reth-network = { workspace = true }
reth-network-peers = { workspace = true }
reth-network-p2p = { workspace = true }
reth-blockchain-tree = { workspace = true }
reth-db = { workspace = true }
reth-evm = { workspace = true }
reth-node-api = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
# unit tests
tn-types = { workspace = true, features = ["test-utils"] }
assert_matches = { workspace = true }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-tracing = { workspace = true }
fastcrypto = { workspace = true }
narwhal-test-utils = { workspace = true }

# integration tests
anemo = { workspace = true }
prometheus = { workspace = true }
narwhal-network = { workspace = true }
narwhal-network-types = { workspace = true }
narwhal-typed-store = { workspace = true }
narwhal-primary = { workspace = true, features = ["test-utils"] }
