name: Rust

on:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt-clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: |
          cargo version
          rustc --version
          cargo fmt --verbose -- --check
    - name: Clippy
      run: |
          cargo version
          rustc --version
          cargo clippy --verbose --all --all-features -- -D warnings

  rust-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: |
          uname -a
          df -h
          free
          cargo version
          rustc --version
          cargo test --all --all-features --workspace --verbose
