name: Rust

on:
  pull_request:

env:
  CARGO_INCREMENTAL: 0 # disable incremental compilation
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  fmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: cargo +nightly fmt
        run: |
          rustc --version
          cargo +nightly version
          cargo +nightly fmt --verbose -- --check
      - name: cargo +nightly clippy
        run: |
          rustc --version
          cargo +nightly version
          cargo +nightly clippy --version
          cargo +nightly clippy --verbose --all --all-features -- -D warnings

  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
      # inspired by https://matklad.github.io/2021/09/04/fast-rust-builds.html#CI-Workflow
      - name: compile
        run: cargo test --no-run --locked
      - name: test default features
        run: cargo test --workspace --no-default-features -- --nocapture --quiet
      - name: test all features
        run: cargo test --workspace --all-features -- --nocapture --quiet
      - name: Run tests with faucet feature
        run: cargo test --workspace --no-default-features --features faucet -- --nocapture --quiet
